<#
.SYNOPSIS
Generates the C# Tutor skill catalog.

.DESCRIPTION
Reads csharp-tutor-manifest.json and each skill's SKILL.md frontmatter, then writes SKILLS.md.
Use -Check in CI or local validation to fail when the checked-in catalog is stale.

.PARAMETER SourceRoot
Repository root. Defaults to the parent folder of this script.

.PARAMETER OutputPath
Catalog path. Defaults to SKILLS.md in the repository root.

.PARAMETER Check
Compares generated content with OutputPath and exits with a non-zero code if it differs.

.EXAMPLE
.\scripts\generate-skills-catalog.ps1

.EXAMPLE
.\scripts\generate-skills-catalog.ps1 -Check
#>
[CmdletBinding()]
param(
    [string]$SourceRoot,
    [string]$OutputPath,
    [switch]$Check
)

$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($SourceRoot)) {
    $SourceRoot = Join-Path $PSScriptRoot ".."
}
$SourceRoot = (Resolve-Path -LiteralPath $SourceRoot).Path

if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    $OutputPath = Join-Path $SourceRoot "SKILLS.md"
}

function Get-FrontmatterValue {
    param(
        [string]$Text,
        [string]$Key
    )

    $match = [regex]::Match($Text, "(?m)^$([regex]::Escape($Key)):\s*(.+)$")
    if ($match.Success) {
        return $match.Groups[1].Value.Trim()
    }

    return ""
}

function Escape-MarkdownTableCell {
    param([string]$Value)

    if ([string]::IsNullOrWhiteSpace($Value)) {
        return ""
    }

    return ($Value -replace '\|', '\|' -replace '\r?\n', ' ').Trim()
}

function Normalize-LineEndings {
    param([string]$Value)

    if ($null -eq $Value) {
        return ""
    }

    return ($Value -replace "\r\n", "`n" -replace "\r", "`n")
}

$manifestFile = Join-Path $SourceRoot "csharp-tutor-manifest.json"
if (-not (Test-Path -LiteralPath $manifestFile)) {
    throw "Manifest not found: $manifestFile"
}

$manifest = Get-Content -LiteralPath $manifestFile -Raw | ConvertFrom-Json
$skills = @()

foreach ($skillName in $manifest.skills) {
    $skillFile = Join-Path $SourceRoot "$skillName\SKILL.md"
    if (-not (Test-Path -LiteralPath $skillFile)) {
        throw "Skill listed in manifest is missing SKILL.md: $skillName"
    }

    $text = Get-Content -LiteralPath $skillFile -Raw
    $frontmatterName = Get-FrontmatterValue -Text $text -Key "name"
    $description = Get-FrontmatterValue -Text $text -Key "description"
    $shortDescription = Get-FrontmatterValue -Text $text -Key "  short-description"

    if ([string]::IsNullOrWhiteSpace($frontmatterName)) {
        $frontmatterName = $skillName
    }

    $skills += [pscustomobject]@{
        Name = $frontmatterName
        Folder = $skillName
        ShortDescription = $shortDescription
        Description = $description
    }
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("# C# Tutor Skill Catalog")
$lines.Add("")
$lines.Add("Generated from ``csharp-tutor-manifest.json`` and skill frontmatter. Do not edit this file by hand; run ``.\scripts\generate-skills-catalog.ps1`` instead.")
$lines.Add("")
$lines.Add("Package version: ``$($manifest.version)``")
$lines.Add("")
$lines.Add("## Skills")
$lines.Add("")
$lines.Add("| Skill | Short description | When to use |")
$lines.Add("| --- | --- | --- |")

foreach ($skill in $skills) {
    $skillLink = "[``$($skill.Name)``]($($skill.Folder)/SKILL.md)"
    $short = Escape-MarkdownTableCell -Value $skill.ShortDescription
    $description = Escape-MarkdownTableCell -Value $skill.Description
    $lines.Add("| $skillLink | $short | $description |")
}

$lines.Add("")
$lines.Add("## Maintenance")
$lines.Add("")
$lines.Add("- Add new skill folders to ``csharp-tutor-manifest.json``.")
$lines.Add("- Keep each ``SKILL.md`` frontmatter ``name`` aligned with its folder name.")
$lines.Add("- Keep ``metadata.short-description`` concise; it appears in this catalog.")
$lines.Add("- Run ``.\scripts\test-csharp-tutor.ps1`` before committing.")
$lines.Add("")

$content = ($lines -join "`r`n")

if ($Check) {
    if (-not (Test-Path -LiteralPath $OutputPath)) {
        Write-Error "Catalog is missing: $OutputPath"
        exit 1
    }

    $existing = Get-Content -LiteralPath $OutputPath -Raw
    $normalizedExisting = (Normalize-LineEndings -Value $existing).TrimEnd()
    $normalizedGenerated = (Normalize-LineEndings -Value $content).TrimEnd()
    if ($normalizedExisting -ne $normalizedGenerated) {
        Write-Error "Catalog is stale. Run .\scripts\generate-skills-catalog.ps1."
        exit 1
    }

    Write-Host "Skill catalog is up to date."
    exit 0
}

Set-Content -LiteralPath $OutputPath -Value $content -Encoding utf8
Write-Host "Generated $OutputPath"
